- README.md
> feat(docs): Document how to do l10n extraction/merge.

- scripts/extract_strings.sh
Related to https://github.com/mozilla/fxa-content-server/issues/2398
> Strings extraction script

- scripts/email-dev-l10n.sh
- scripts/extract_strings.sh
- scripts/stats-po.sh
> fix(email): add a script to send a string update message to the l10n list

- locale/templates/LC_MESSAGES/client.pot
- locale/templates/LC_MESSAGES/server.pot
> merge strings for train 42

- locale/pl/LC_MESSAGES/client.po
- locale/pl/LC_MESSAGES/server.po
Hi,
I'm a new member of the Polish localization team. I noticed that Firefox Accounts translation is out of date, so here is a full update.
> Updated Polish (pl) localization of Firefox Accounts

- locale/kk/LC_MESSAGES/client.po
- locale/kk/LC_MESSAGES/server.po
Added initial Kazakh translation.
> Add Kazakh (kk) translation.

- README.md
- locale/sr_Latn/LC_MESSAGES/client.po
- locale/sr_Latn/LC_MESSAGES/server.po
- scripts/extract_strings.sh
> fix(l10n): convert sr to sr_Latn automatically

- locale/sq/LC_MESSAGES/client.po
- locale/sq/LC_MESSAGES/server.po
Hope this time things are right.
> Updating sq locale

- README.md
- locale/hi/LC_MESSAGES/client.po
- locale/hi/LC_MESSAGES/server.po
- locale/hi/client.po
- locale/hi/server.po
- locale/pt/LC_MESSAGES/client.po
- locale/pt/LC_MESSAGES/server.po
- locale/sr_Latn/LC_MESSAGES/client.po
- locale/sv/LC_MESSAGES/server.po
- scripts/before_prod_deploy.sh
> fix(locale): copies locales that are not translated externally

- locale/pl/LC_MESSAGES/client.po
> Updated Polish (pl) localization of Firefox Accounts for train 52

- locale/pl/LC_MESSAGES/client.po
> Updated Polish (pl) localization of Firefox Accounts for train 57

- locale/pl/LC_MESSAGES/client.po
- locale/pl/LC_MESSAGES/server.po
> Updated Polish (pl) localization of Firefox Accounts for train 58

- locale/pl/LC_MESSAGES/client.po
- locale/pl/LC_MESSAGES/server.po
> Updated Polish (pl) localization of Firefox Accounts for train 59

- locale/de/LC_MESSAGES/server.po
- locale/en/LC_MESSAGES/server.po
- locale/es/LC_MESSAGES/server.po
- locale/fr/LC_MESSAGES/server.po
- locale/ja/LC_MESSAGES/server.po
- locale/ru/LC_MESSAGES/server.po
- locale/zh_CN/LC_MESSAGES/server.po
* de, en, es, fr, ja, ru, zh_CN
> feat(strings): Add the location template strings for some locales.

- locale/de/LC_MESSAGES/server.po
- locale/en/LC_MESSAGES/server.po
- locale/es/LC_MESSAGES/server.po
- locale/fr/LC_MESSAGES/server.po
- locale/ja/LC_MESSAGES/server.po
- locale/ru/LC_MESSAGES/server.po
- locale/zh_CN/LC_MESSAGES/server.po
For en, de, es, fr, ja, ru, hz_CN
> feat(l10n): Add the suspicious location translations.

- locale/pl/LC_MESSAGES/client.po
- locale/pl/LC_MESSAGES/server.po
> Updated Polish (pl) localization of Firefox Accounts for train 60

- locale/pl/LC_MESSAGES/client.po
- locale/pl/LC_MESSAGES/server.po
- locale/sl/LC_MESSAGES/server.po
> Updated Polish (pl) localization of Firefox Accounts for train 61

- locale/pl/LC_MESSAGES/client.po
- locale/pl/LC_MESSAGES/server.po
> Updated Polish (pl) localization of Firefox Accounts for train 62

- locale/lt/LC_MESSAGES/server.po
> fix(locale): adjust plural forms for lt

- scripts/merge_po.sh
fixes mozilla/fxa-content-server#3795
@vladikoff - r?
> fix(scripts): Set the output width to 200 charcters

- locale/pl/LC_MESSAGES/client.po
- locale/pl/LC_MESSAGES/server.po
> Updated Polish (pl) localization of Firefox Accounts for train 63

- scripts/extract_strings.sh
@shane-tomlinson r?
Connects to https://github.com/mozilla/fxa-content-server/issues/3802
> fix(l10n): remove old server.pot and use a fresh one each extraction

- locale/pl/LC_MESSAGES/client.po
> Updated Polish (pl) localization of Firefox Accounts for train 64

- locale/pl/LC_MESSAGES/client.po
- locale/pl/LC_MESSAGES/server.po
> Update Polish (pl) localization of Firefox Accounts for train 65

- locale/pl/LC_MESSAGES/client.po
> Update Polish (pl) localization of Firefox Accounts for train 66

- locale/pl/LC_MESSAGES/client.po
- locale/pl/LC_MESSAGES/server.po
> Update Polish (pl) localization of Firefox Accounts for train 67

- .travis.yml
> chore(travis): drop node 0.10 support in Travis

- locale/zh_TW/LC_MESSAGES/client.po
> fix(zh_TW): Remove the extra >

- locale/cy/LC_MESSAGES/client.po
> fix cy locale

- .travis.yml
- circle.yml
- package.json
> fix(deps): Update the deps to get rid of most nsp warnings, only use node 8

- locale/fr/LC_MESSAGES/client.po
> fix(fr): Fix the broken password list link in fr

- locale/pa_IN/LC_MESSAGES/server.po
> fix(pa_IN): Fix the broken links in pa_IN

- .travis.yml
> chore(ci): Add pbooth to the list of test failure email recipients.

- locale/eu/LC_MESSAGES/client.po
> fix(eu): Fix the TOTP support link error in basque.

- scripts/extract-and-pull-request.sh
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1547332
> Fix string extraction script

- .circleci/config.yml
The Lambda function has been removed, moving to a cron build
> Move to Circle cron build

- locale/bn/LC_MESSAGES/client.po
- locale/bn/LC_MESSAGES/server.po
issue #358
cc @peiying2 - I copied over the blank templates into the bn directory, I wasn't sure if they should be pre-populated with one of the existing bn-* locales and didn't want to anger anyone.
> feat(bn): Add a new locale directory, `bn`

- package-lock.json
- package.json
Update to the latest grunt-l10n-lint which handled self-closing tags.
> fix(lint): Fix the errors on the br elements.

- .circleci/config.yml
- scripts/extract-and-pull-request.sh
might fix https://github.com/mozilla/fxa/issues/5268
> update circleci to node 12

- locale/templates/settings.ftl
This commit add the initial set of strings from FxA's new settings frontend.
> chore(l10n): add initial ftl from new settings

- scripts/extract-and-pull-request.sh
- scripts/extract_strings.sh
Update scripts to extract *.ftl files from fxa-settings.
Please do not merge yet!  We'd like to have the one ftl file in fxa-setting reviewed before merging.
> chore(scripts): update scripts to extract *.ftl from fxa-settings

- scripts/extract-and-pull-request.sh
To enable https://github.com/mozilla/fxa/pull/7588
> add fxa-settings build step

- locale/templates/settings.ftl
* Fixes for bugs #470 and #473
* Sentence case adjustments to match the designs
> Pull in settings updates

- locale/templates/settings.ftl
@peiying2 Here's a fix for that stale ID from #475
> Update a stray stale l10n ID

- .circleci/config.yml
Cocomo is requesting this time change
> change extraction time to thursday afternoons

- scripts/extract-and-pull-request.sh
- scripts/extract_strings.sh
> fxa(chore): disable auth ftl

- locale/de/auth.ftl
Closes #548
----
Within `mozilla/fxa`:
- Closes [11783](https://github.com/mozilla/fxa/issues/11783)
- Closes [11784](https://github.com/mozilla/fxa/issues/11784) 
- Closes [11785](https://github.com/mozilla/fxa/issues/11785)
> fix(content-server-l10n): fix errors in German translations

- .github/workflows/l10n_extract.yaml
Workaround for an intermittent failure caused by an issue in the gh cli.
> Workflow fix
