- locale/it/LC_MESSAGES/client.po
`Scarica Firefox per dispositivi <em>mobile</em>.` =>
`Scarica Firefox per dispositivi mobile.`
@mathjazz - could you review this? I found the extra tag while working on a linting tool (see https://github.com/mozilla/grunt-l10n-lint)
> Remove unexpected `em` tags in the Italian translation.

- locale/pl/LC_MESSAGES/client.po
I'm leaving untranslatable strings in client.po out for now (issue #104).
Also, I wasn't sure what to do about the two new strings in server.po. Are you sure they should be marked for translation?
@splewako
> Updated Polish (pl) localization of Firefox Accounts for train 56

- locale/ja/LC_MESSAGES/client.po
Remove the /ja/ in the middle of the link, as well as the trailing slash.
> fix(ja): Fix the unexpected link.

- locale/templates/LC_MESSAGES/.gitignore
> fix(git): Only ignore client.pot and server.pot in templates/LC_MESSAGES

- locale/es/LC_MESSAGES/client.po
A space was missing between `a` and `%(escapedBackLinkAttrs)s`
> fix(es): Fix the broken link in es.

- locale/fr/LC_MESSAGES/server.po
@shane-tomlinson @vladikoff Never fixed an l10n issue before so not sure if this is the right process?
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1542704
> fix(l10n): fix french translation for post change primary email

- scripts/extract-and-pull-request.sh
- scripts/extract_strings.sh
We're transitioning the `fxa-auth-server` to an updated email system, part of which includes using Fluent.
This PR (hopefully) updates the scripts to look for FTL files in the auth-server.
> retrieve ftl files in fxa-auth-server

- .circleci/config.yml
The build CI job is [failing](https://app.circleci.com/pipelines/github/mozilla/fxa-content-server-l10n/3768/workflows/447187b5-cf18-43f3-96c9-7439842f90ca/jobs/10016) right now:
> [Error: {"message":"Must specify access token via Authorization header. https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param","documentation_url":"https://docs.github.com/v3/#oauth2-token-sent-in-a-header"}] {
code: 400
}
Problem is, this script utilizes the deprecated [gh](https://www.npmjs.com/package/gh) CLI. However, it was on version 1.12.14, and the most recent (and last) version is 2.8.9, so my hope is that they addressed this issue in that time.
If this fails I've started working on a new version of the script that uses the official [GH CLI](https://cli.github.com/), but …
> upgrade deprecated gh cli version

- scripts/ci-creds.js
Hopefully fixes the most recent build failure, according to [this](https://github.com/node-gh/gh/issues/755)
> specify use_editor:false for gh cli

- scripts/extract-and-pull-request.sh
- scripts/extract_strings.sh
Now that auth.ftl has been merged, we can re-enable the extraction from the auth server.
> Enable auth-server extract strings/extract and PR commands

- locale/de/auth.ftl
- Per [QA feedback](https://mozilla-hub.atlassian.net/browse/FXA-4505), there are unnecessary `$` at the end of the sentences within the `subscriptionDowngrade` and `subscriptionUpgrade` emails.
- Removes the unnecessary characters.
> fix(content-server-l10n): Remove dollar sign from end of sentence - German

- scripts/extract_strings.sh
@clouserw commented out these lines yesterday:
```
#(cd $MAILER_DIR && rm -f server.pot && npx grunt l10n-extract)
#cp $MAILER_DIR/server.pot $CONTENT_DIR/locale/templates/LC_MESSAGES/
```
This was failing because after mozilla/fxa/pull/12390, the auth-server no longer has an `l10n-extract` grunttask. We can indeed remove these from the script.
Since the 2nd line gave me pause as it references the `fxa-content-sever`, I tested that the extraction for the content server, which still has a few translations in `server.po`, still works as expected locally by deleting the `locale` directory, changing a string in a content-server `server/` directory, running `l10n-extract` in content-server, and seeing the new string in `locale/templates/server.po`. In this script, after that grunttask is ran, …
> Remove commented out lines in extract_strings.sh

- scripts/extract_strings.sh
There's been some discussion lately on whether or not we _want_ to rely purely on fallback text for en/en-US users, as we have been since setting Fluent up in FxA as far as I know. We had a recent bug show us that English/US users were actually very likely seeing `en-GB` locales (see [more info here](https://github.com/mozilla/fxa/pull/12861#issuecomment-1125440236)), and since changing the Fluent strategy to be more precise in its matching, our fallback text is showing as expected. However, we keep uncovering instances where we haven't supplied fallback text, which has created several fairly severe (from a UI point of view) bugs, the newest few coming up today.
While discussions on how we handle fallback text are still ongoing and at the time of writing we want to always supply fallback …
> Include en and en-US FTL files in locale/

- scripts/extract_strings.sh
The script is checking hashes before and after extraction, but the extraction process doesn't automatically copy over the files in the l10n repo.
> Fix extraction for GetText files

- .github/linter_config.yml
- .github/requirements.txt
- .github/workflows/reference_linter.yaml
I've added checks for hard-coded brand names in a new version of the linter
https://github.com/mozilla-l10n/moz-fluent-linter/pull/5
All of the exceptions should have been terms :-(
> Update reference linter, check for hard-coded brand names

- .github/requirements.txt
- .github/scripts/detect_unchanged_ids.py
- .github/workflows/reference_linter.yaml
Revised PR based on feedback from #615
- Now uses compare-locales to parse
- Bash script no longer changes filenames, instead moves files to old/ and new/ folders
- Integrated into reference locale linter action
> Linter: check for string changes without new IDs

- scripts/merge_po.sh
Output looks correct from a [test here](https://github.com/mozilla/fxa-content-server-l10n/pull/638)
Turns out we have a few… (-200k lines) 😨
> Export: Remove obsolete strings from localized .po files

- .github/workflows/l10n_extract.yaml
With [this PR and change]( https://github.com/mozilla/fxa/pull/14312/files#diff-7476db00402b40902a9cf3a6834136ed6356ae6591cb4c40a2ed99c2c0a5464fR22), we're using grunt instead of webpack to create our `settings.ftl` file. Webpack required a full build to concat our files, and while `build` still works, since it's now separate from webpack we can run the grunt task instead to make this workflow slightly faster.
> Simplify fxa-settings extract strings command

- scripts/extract_strings.sh
Linked to [PR-14429](https://github.com/mozilla/fxa/pull/14429)
Because:
- We are standardizing the default locale for all fxa packages to en.
This commit:
- Change the fluent extraction source from $SETTINGS_DIR/public/locales/en-US/*.ftl to $SETTINGS_DIR/public/locales/en/*.ftl
Closes #FXA-6003
> feat(fxa-settings): Change fxa-settings default locale from en-US to en

- scripts/extract_strings.sh
PR linked with [Fxa PR-14567](https://github.com/mozilla/fxa/pull/14567) - awaiting review, these two PRs should only be merged when both approved
In response to [FXA-14548 on GitHub](https://github.com/mozilla/fxa/issues/14548)/[#FXA-6388 on Jira](https://mozilla-hub.atlassian.net/browse/FXA-6388)
Because:
- Strings from shared components and branding that were concatenated into multiple packages before string extraction were causing duplication on Pontoon.
This commit:
- Add Fluent String extraction for two more dir (`fxa-react` and `fxa-shared`)
- Extract strings from specific files (e.g., change `*.ftl` to `payments.ftl`)
> Extract strings from fxa-react, fxa-shared

- .github/workflows/l10n_extract.yaml
Because fxa-react and fxa-shared needed to be added to the workflow file to successfully extract strings from these directories.
Fixes this error in workflow:
```
Checking ./fxa-react.. Error: No such directory
Error: Process completed with exit code 1.
```
> add fxa-react and fxa-shared dir to workflow

- .github/workflows/l10n_extract.yaml
Because:
- Changes were introduced into fxa to only clone the l10n repo once via _scripts/l10n/clone.sh
This Commit:
- Updates the workflow  to call this script before the build step to extract text
> chore(l10n): call clone.sh in workflow to align with fxa script changes

- .github/workflows/l10n_extract.yaml
- scripts/extract_strings.sh
Because:
* The FXA shared branding file was moved from ./packages/fxa-shared/l10n to ./libs/shared/l10n
This commit:
* Updates github workflow and extract_strings script with the new location of the shared branding ftl
* Related fxa PR is [mozilla/fxa/pull/15798](https://github.com/mozilla/fxa/pull/15798)
Closes #FXA-8228
> feat(shared): update extract with new branding loc

- .github/workflows/l10n_extract.yaml
- scripts/extract_strings.sh
Because:
- The Subscription Platform team is adding a new app service, payments-next, to replace the existing fxa-payments-server. In the short term both payments-next and fxa-payments-server need to be supported, each utilizing different ftl strings.
This commit:
- Adds support for new app payments-next utilizing payments-next.ftl
Closes #FXA-7482
> feat(next): add support for payments-next.ftl
